version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'baby_go_development' #この名前でデータベースが作成される
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものに変更
    volumes:
      - mysql_data:/var/lib/mysql #データの永続化
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d #テストデータベース作成ファイルをマウント

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/myapp:cached
      # vendor以下などホストと連携しなくてもよいものを、上書きして永続化の対象外にする。
      # exclude volumes
      - /myapp/vendor
      - /myapp/log
      - /myapp/.git
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    stdin_open: true
    tty: true

  chrome:
    image: selenium/standalone-chrome:3.141.59
    ports:
      - 4444:4444

volumes:
  mysql_data: #名前付きボリュームの登録